In [3]:
import numpy as np

In [ ]:
pf_i = {
    

}

pv_f = {
    
    
}

In [26]:
x = np.array([0.1,0.1,0.2,0.3,0.1,0.1,0.1])
y = np.array([0.0,0.4,0.1,0.1,0.1,0.2,0.1])

In [27]:
np.sum(y)

0.9999999999999999

In [28]:
arr = y-x

In [13]:
arr

array([-0.1,  0.2, -0.1, -0.2,  0. ,  0.1,  0. ])

In [15]:
list(arr)

[-0.1, 0.19999999999999998, -0.1, -0.19999999999999998, 0.0, 0.1, 0.0]

In [29]:
arr = np.around(arr, decimals=5)

In [36]:

neg_arr = []
for i in arr:
    if i<0:
        neg_arr.append(i)

In [38]:
def 
    pos_arr = []
    for i in arr:
        if i>0:
            pos_arr.append(i)

In [35]:
pos_arr

[0.3, 0.1]

In [44]:
neg_arr = np.sort(neg_arr)

In [45]:
pos_arr = -np.sort(-np.array(pos_arr))

In [46]:
neg_arr

array([-0.2, -0.1, -0.1])

In [47]:
pos_arr

array([0.3, 0.1])